// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ8vJdrQvMK6myYlH2AQeTIx6pb9P8x7c',
    appId: '1:288631304060:web:a3db0e86ccbe058f5e3ef9',
    messagingSenderId: '288631304060',
    projectId: 'availability-b12af',
    authDomain: 'availability-b12af.firebaseapp.com',
    databaseURL: 'https://availability-b12af-default-rtdb.firebaseio.com',
    storageBucket: 'availability-b12af.appspot.com',
    measurementId: 'G-12TRFR520Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmAV4DI2FFf62sVtnQrQuvD4klFVQp4-c',
    appId: '1:288631304060:android:4fb971cbb322d1285e3ef9',
    messagingSenderId: '288631304060',
    projectId: 'availability-b12af',
    databaseURL: 'https://availability-b12af-default-rtdb.firebaseio.com',
    storageBucket: 'availability-b12af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkye7kUw5fUk6qSC0ExAzHhuIEETuoBNU',
    appId: '1:288631304060:ios:f3bcb0c7d627f24f5e3ef9',
    messagingSenderId: '288631304060',
    projectId: 'availability-b12af',
    databaseURL: 'https://availability-b12af-default-rtdb.firebaseio.com',
    storageBucket: 'availability-b12af.appspot.com',
    androidClientId: '288631304060-2f4iu62mohg2s2v6gscglsgrbk985b4m.apps.googleusercontent.com',
    iosClientId: '288631304060-g48dnkbu9s4d10n4lijqflm1uiqsot1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.redwinners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkye7kUw5fUk6qSC0ExAzHhuIEETuoBNU',
    appId: '1:288631304060:ios:f3bcb0c7d627f24f5e3ef9',
    messagingSenderId: '288631304060',
    projectId: 'availability-b12af',
    databaseURL: 'https://availability-b12af-default-rtdb.firebaseio.com',
    storageBucket: 'availability-b12af.appspot.com',
    androidClientId: '288631304060-2f4iu62mohg2s2v6gscglsgrbk985b4m.apps.googleusercontent.com',
    iosClientId: '288631304060-g48dnkbu9s4d10n4lijqflm1uiqsot1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.redwinners',
  );
}
